### ISSUE TITLE
Missing Upload Button 1.1.0

### ISSUE THREAD

**Issue by fyrebase** [smcyr/Craft-FocusPoint#6] opened 2016-07-23 02:03 UTC
Upload button has disappeared from modal when selecting an image. It is present in 1.0.6

**Comment by wfendler** [comment] 2016-08-04 19:16
I know absolutely nothing about plugin development but after going through the 1.1.0 commits my guess is that it's somewhere in this commit 83b36753922a4bb2ca12543289a19f976aeee758

That seems to be doing a lot more with the database and plugin initializing. All the other commits seemed to be more focused on refactoring `focusX` and `focusY` naming and calculations as well as some CSS updates to the focus point button.

So anyone with more plugin knowledge maybe start at 83b36753922a4bb2ca12543289a19f976aeee758
I did my best to hone in on the problem `/shrug`!

**Comment by mikestecker** [comment] 2016-08-04 23:01
@wfendler it looks like it went missing when you removed the line:

`Craft.registerElementIndexClass('FocusPoint_Asset', Craft.AssetIndex);` in https://github.com/smcyr/Craft-FocusPoint/commit/6a73a5e480c0a27d3fbe1e18db16f16a09b2ff3a

**Comment by smcyr** [comment] 2016-08-05 14:07
@fyrebase Thanks for reporting this!
@mikestecker Thanks for finding the cause for the problem.
It's now fixed, so I will close this issue.

**Closed by smcyr** 2016-08-05 14:07 UTC
